widget_sources = [
  '__init__.py',
  'window.py',
  'shortcuts.py'
]

install_data(widget_sources, install_dir: moduledir / 'widgets')

subdir('containers')
subdir('pages')

subdir('preferences')
subdir('manga')
subdir('source')
subdir('extension')
subdir('chapter')
subdir('reader')
subdir('download')